name: "clj-Holmes"

on: workflow_dispatch

permissions:
  contents: read
  
jobs:
  clj-holmes:
    name: Run clj-holmes scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan code
        uses: clj-holmes/clj-holmes-action@main
        with:
#           rules-repository: 'git://org/private-rules-repo#main'
          output-type: 'sarif'
          output-file: 'clj-holmes-results.sarif'
          fail-on-result: 'false'

      - name: Upload analysis results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{github.workspace}}/clj-holmes-results.sarif
          wait-for-processing: true
          
      - name: Dependencies scan
        uses: clj-holmes/clj-watson-action@main
        with:
          clj-watson-sha: "9972a33"
          clj-watson-tag: "v4.0.0"
          database-strategy: github-advisory
          deps-edn-path: 'deps.edn'
